version: '2'
services:

  # SQL database
  postgres:
    image: "library/postgres:latest"
    restart: "always"
    volumes:
      - "ktor-starter-data:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "ktor-starter"
    mem_limit: "8g"

volumes:
  ktor-starter-data: